/*jshint esversion: 6 */


export default {
    "coptic": [
      "authors.copticname",
      "titles.text",
      "colophons.text"
    ],
    "greek": [
      "authors.greekname"
    ],
    "hidden": [
      "manuscripts.creator",
      "collections.creator",
      "collections.cmclname",
      "works.id",
      "works.creator",
      "works.shelfmarks",
      "works.period",
      "works.problems",
      "titles.creator",
      "titles.taggedtext",
      "colophons.creator",
      "authors.id",
      "authors.creator",
      "authors.cmclname",
      "editors.cmclname",
      "places.creator",
      "places.hasplans",
      "places.hasphotos",
      "persons.id",
      "persons.creator",
      "biblio.creator",
      "biblio.editors",
      "m_quires.id",
      "m_hands.id",
      "m_placephase.id",
      "m_msplaces.id"
    ],
    "id_fld": {
      "manuscripts": "id",
      "collections": "fullname",
      "works": "cmcl",
      "titles": "cc",
      "colophons": "id",
      "authors": "name",
      "places": "name",
      "persons": "name"
    },
    "searchDefault": {
      "manuscripts": "id",
      "collections": "fullname",
      "works": "cmcl",
      "titles": "cc",
      "colophons": "id",
      "authors": "name",
      "places": "m_toponyms:toponym",
      "persons": "name"
    },
    "preview": {
      "manuscripts":  [ "id", "cmclid", "tm", "ldab", "bookform", "writingsupport" ],
      "collections":  [ "id", "fullname", "cmclname", "country", "town", "institution", "name", "notes" ],
      "works":        [ "id", "cmcl", "title", "cpg" ],
      "titles":       [ "cc", "type", "workcc", "msid" ],
      "colophons":    [ "id", "msid", "dialect", "chronofrom", "chronoto", "datingcriteria" ],
      "authors":      [ "name", "title", "copticname", "greekname", "cmclname" ],
      "places":       [ "id", "name", "tmgeo", "pleiades", "region", "area", "episcopalsee" ],
      "persons":      [ "id", "name", "type", "profession", "patronymic" ]
    },
    "label": {
      "manuscripts": "Manuscripts",
      "collections": "Collections",
      "works": "Works",
      "titles": "Titles",
      "colophons": "Colophons",
      "authors": "Authors",
      "places": "Places",
      "persons": "Persons attested in colophons"
    },

    "fld_whitelist": [
        "places:id",
        "places:name",
        "places:tmgeo",
        "places:pleiades",
        "places:region",
        "places:area",
        "places:meris",
        "places:nomos",
        "places:province",
        "places:episcopalsee",
        "places:typology",
        "places:description",
        "places:hasmonastery",
        "places:isnomoscapital",
        "places:status",

        "m_toponyms:toponym",
        "m_placephase:fperiod",
        "m_placephase:ftypology",

        "works:id",
        "works:cmcl",
        "works:title",
        "works:cpg",
        "works:cant",
        "works:cavt",
        "works:bho",
        "works:bhg",
        "works:bhl",
        "works:cae",

        "works:litperiod",
        "m_wkauthors:type",
        "m_wkauthors:author",

        "authors:id",
        "authors:name",
        "authors:copticname",
        "authors:greekname",
        "authors:viaf",
        "authors:title",
        "authors:status",

        "titles:id",
        "titles:cc",
        "titles:workcc",
        "titles:msid",
        "titles:type",
        "titles:text",
        "titles:translation",

        "colophons:id",
        "colophons:msid",
        "colophons:chronofrom",
        "colophons:chronoto",
        "colophons:istitutionplace",
        "colophons:dialect",
        "colophons:dialectnotes",
        "colophons:greektext",
        "colophons:writingaxis",
        "colophons:cryptography",
        "colophons:minusculecopitc",
        "colophons:minusculegreek",
        "colophons:text",
        "colophons:translation",

        "collections:id",
        "collections:fullname",
        "collections:country",
        "collections:town",
        "collections:institution",
        "collections:name",

        "manuscripts:id",
        "m_shelfmarks:collection",
        "m_shelfmarks:shelfmark",
        "manuscripts:cmclid",
        "manuscripts:tm",
        "manuscripts:ldab",
        "manuscripts:lcbm",
        "manuscripts:dbmnt",
        "manuscripts:alias",
        "manuscripts:issinglefrag",
        "manuscripts:isbookbinding",
        "manuscripts:reusedinbinding",
        "manuscripts:stratigraphy",
        "manuscripts:modernhistory",
        "manuscripts:contents",
        "manuscripts:dialect",
        "manuscripts:chronofrom",
        "manuscripts:chronoto",
        "manuscripts:datingsource",
        "manuscripts:datingcriteria",
        "manuscripts:bookform",
        "manuscripts:writingsupport",
        "m_msplaces:place",
        "m_msplaces:type",
        "m_msplaces:sourceinfo",
        "manuscripts:leaftotextant",
        "manuscripts:fragtot",
        "manuscripts:fragdim",
        "manuscripts:leaftotestimated",
        "manuscripts:quiresextant",
        "manuscripts:gennotes",
        "manuscripts:columns",
        "manuscripts:colnotes",
        "manuscripts:linespercolumn",
        "manuscripts:charsperline",
        "manuscripts:leafw",
        "manuscripts:leafh",
        "manuscripts:framew",
        "manuscripts:frameh",
        "manuscripts:intercolumnium",
        "manuscripts:marginup",
        "manuscripts:marginlow",
        "manuscripts:marginout",
        "manuscripts:marginin",
        "manuscripts:marginleft",
        "manuscripts:marginright",
        "manuscripts:heighttenlines",
        "manuscripts:prophw",
        "manuscripts:propwt",
        "manuscripts:quiresig",
        "manuscripts:quiretype",
        "manuscripts:quireposition",
        "m_quires:quirepaptype",
        "m_quires:quirepartype",
        "manuscripts:pagination",
        "manuscripts:pagtype",
        "manuscripts:pagposition",
        "manuscripts:foliation",
        "manuscripts:foltype",
        "manuscripts:folposition",
        "manuscripts:handstot",
        "manuscripts:lectionalsigns",
        "manuscripts:structuralsigns",
        "manuscripts:signsnotes",
        "manuscripts:abbreviations",
        "manuscripts:ruling",
        "manuscripts:rulingtype",
        "manuscripts:rulingtool",
        "manuscripts:pricking",
        "manuscripts:leaftabs",
        "manuscripts:kolleseis",
        "manuscripts:kolleseseisdescr",
        "manuscripts:kollno",
        "manuscripts:kolldim",
        "manuscripts:bindings",
        "manuscripts:bindformer",
        "manuscripts:boardw",
        "manuscripts:boardh",
        "manuscripts:boardt",
        "manuscripts:spinew",
        "manuscripts:sewings",
        "manuscripts:sewingtype",
        "manuscripts:sewingstationsno",
        "manuscripts:foldpattern",
        "manuscripts:boardmat",
        "manuscripts:boardfeatures",
        "manuscripts:boardattachment",
        "manuscripts:covers",
        "manuscripts:covermat",
        "manuscripts:turnins",
        "manuscripts:mitres",
        "manuscripts:foreedgeflap",
        "manuscripts:coverdecoration",
        "manuscripts:splinelining",
        "manuscripts:endbandtype",
        "manuscripts:fasteningtype",
        "manuscripts:othertiesposition",
        "manuscripts:marginalnotes",
        "manuscripts:greekminuscule",
        "manuscripts:palimpsest",
        "manuscripts:restancient",
        "manuscripts:restmodern",
        "manuscripts:pgmcol",
        "manuscripts:pgmlocation",
        "manuscripts:blktype",
        "manuscripts:blklocation",
        "manuscripts:decortype",
        "manuscripts:decorsubj",
        "manuscripts:decorationdescr",
        "manuscripts:enlargedinitials",
        "manuscripts:sourceinfo",
        "manuscripts:status",
        "m_hands:handno",
        "m_hands:modulartypology",
        "m_hands:writingaxis",
        "m_hands:thickandthin",
        "m_hands:identification",
        "m_hands:writingnotes",

        "m_biblio:short",
        "m_biblio:details",

        "persons:id",
        "persons:name",
        "persons:type",
        "persons:profession",
        "persons:patronymiccarnal",
        "persons:patronymicspirit",
        "persons:hasbrother",
        "persons:hasfather",
        "persons:placebirth",
        "persons:placeaffiliation",
        "persons:sex",
        "persons:datefrom",
        "persons:dateto",

      ]

  , rpp: 30
};
